# compose config on latest release builds
services:
  jupyter:
    container_name: qs-jupyter
    image: notebook:qsafe
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=123
    networks:
      - safe-tier
networks:
  safe-tier:
volumes:
  program-artifacts:
  host-shm:
  host-log:
